const data = [
  {
    id: 1,
    name: "The Great Gatsby",
    price: 10.99,
    description: "A novel by F. Scott Fitzgerald",
    category: "Fiction",
  },
  {
    id: 2,
    name: "To Kill a Mockingbird",
    price: 12.49,
    description: "A novel by Harper Lee",
    category: "Fiction",
  },
  {
    id: 3,
    name: "1984",
    price: 8.99,
    description: "A dystopian novel by George Orwell",
    category: "Science Fiction",
  },
  {
    id: 4,
    name: "The Catcher in the Rye",
    price: 9.99,
    description: "A novel by J.D. Salinger",
    category: "Fiction",
  },
  {
    id: 5,
    name: "Harry Potter and the Philosopher's Stone",
    price: 11.99,
    description: "A novel by J.K. Rowling",
    category: "Fantasy",
  },
  {
    id: 6,
    name: "Pride and Prejudice",
    price: 7.99,
    description: "A novel by Jane Austen",
    category: "Fiction",
  },
  {
    id: 7,
    name: "The Hobbit",
    price: 14.99,
    description: "A fantasy novel by J.R.R. Tolkien",
    category: "Fantasy",
  },
  {
    id: 8,
    name: "The Lord of the Rings",
    price: 19.99,
    description: "A fantasy novel by J.R.R. Tolkien",
    category: "Fantasy",
  },
  {
    id: 9,
    name: "The Da Vinci Code",
    price: 13.49,
    description: "A mystery thriller novel by Dan Brown",
    category: "Thriller",
  },
  {
    id: 10,
    name: "The Alchemist",
    price: 10.49,
    description: "A novel by Paulo Coelho",
    category: "Fiction",
  },
  {
    id: 11,
    name: "The Hitchhiker's Guide to the Galaxy",
    price: 9.79,
    description: "A science fiction comedy novel by Douglas Adams",
    category: "Science Fiction",
  },
];
export default data;
